//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Presentacion.ServicioImportacionesRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoSolicitante", Namespace="http://schemas.datacontract.org/2004/07/WCF_Importacion")]
    [System.SerializableAttribute()]
    public partial class DtoSolicitante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeNacimiento {
            get {
                return this.FechaDeNacimientoField;
            }
            set {
                if ((this.FechaDeNacimientoField.Equals(value) != true)) {
                    this.FechaDeNacimientoField = value;
                    this.RaisePropertyChanged("FechaDeNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProyecto", Namespace="http://schemas.datacontract.org/2004/07/WCF_Importacion")]
    [System.SerializableAttribute()]
    public partial class DtoProyecto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadDeIntegrantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExperienciaPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDePresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoConseguidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoSolicitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeDeInteresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioPorCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDeEquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadDeIntegrantes {
            get {
                return this.CantidadDeIntegrantesField;
            }
            set {
                if ((this.CantidadDeIntegrantesField.Equals(value) != true)) {
                    this.CantidadDeIntegrantesField = value;
                    this.RaisePropertyChanged("CantidadDeIntegrantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cuotas {
            get {
                return this.CuotasField;
            }
            set {
                if ((this.CuotasField.Equals(value) != true)) {
                    this.CuotasField = value;
                    this.RaisePropertyChanged("Cuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExperienciaPersonal {
            get {
                return this.ExperienciaPersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.ExperienciaPersonalField, value) != true)) {
                    this.ExperienciaPersonalField = value;
                    this.RaisePropertyChanged("ExperienciaPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDePresentacion {
            get {
                return this.FechaDePresentacionField;
            }
            set {
                if ((this.FechaDePresentacionField.Equals(value) != true)) {
                    this.FechaDePresentacionField = value;
                    this.RaisePropertyChanged("FechaDePresentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitante {
            get {
                return this.IdSolicitanteField;
            }
            set {
                if ((this.IdSolicitanteField.Equals(value) != true)) {
                    this.IdSolicitanteField = value;
                    this.RaisePropertyChanged("IdSolicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgURL {
            get {
                return this.ImgURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgURLField, value) != true)) {
                    this.ImgURLField = value;
                    this.RaisePropertyChanged("ImgURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoConseguido {
            get {
                return this.MontoConseguidoField;
            }
            set {
                if ((this.MontoConseguidoField.Equals(value) != true)) {
                    this.MontoConseguidoField = value;
                    this.RaisePropertyChanged("MontoConseguido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoSolicitado {
            get {
                return this.MontoSolicitadoField;
            }
            set {
                if ((this.MontoSolicitadoField.Equals(value) != true)) {
                    this.MontoSolicitadoField = value;
                    this.RaisePropertyChanged("MontoSolicitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeDeInteres {
            get {
                return this.PorcentajeDeInteresField;
            }
            set {
                if ((this.PorcentajeDeInteresField.Equals(value) != true)) {
                    this.PorcentajeDeInteresField = value;
                    this.RaisePropertyChanged("PorcentajeDeInteres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioPorCuota {
            get {
                return this.PrecioPorCuotaField;
            }
            set {
                if ((this.PrecioPorCuotaField.Equals(value) != true)) {
                    this.PrecioPorCuotaField = value;
                    this.RaisePropertyChanged("PrecioPorCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeEquipo {
            get {
                return this.TipoDeEquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeEquipoField, value) != true)) {
                    this.TipoDeEquipoField = value;
                    this.RaisePropertyChanged("TipoDeEquipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioImportacionesRef.IServicioImportacion")]
    public interface IServicioImportacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/ImportarSolicitantes", ReplyAction="http://tempuri.org/IServicioImportacion/ImportarSolicitantesResponse")]
        MVC_Presentacion.ServicioImportacionesRef.DtoSolicitante[] ImportarSolicitantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/ImportarSolicitantes", ReplyAction="http://tempuri.org/IServicioImportacion/ImportarSolicitantesResponse")]
        System.Threading.Tasks.Task<MVC_Presentacion.ServicioImportacionesRef.DtoSolicitante[]> ImportarSolicitantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/ImportarProyectos", ReplyAction="http://tempuri.org/IServicioImportacion/ImportarProyectosResponse")]
        MVC_Presentacion.ServicioImportacionesRef.DtoProyecto[] ImportarProyectos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioImportacion/ImportarProyectos", ReplyAction="http://tempuri.org/IServicioImportacion/ImportarProyectosResponse")]
        System.Threading.Tasks.Task<MVC_Presentacion.ServicioImportacionesRef.DtoProyecto[]> ImportarProyectosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioImportacionChannel : MVC_Presentacion.ServicioImportacionesRef.IServicioImportacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioImportacionClient : System.ServiceModel.ClientBase<MVC_Presentacion.ServicioImportacionesRef.IServicioImportacion>, MVC_Presentacion.ServicioImportacionesRef.IServicioImportacion {
        
        public ServicioImportacionClient() {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImportacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioImportacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Presentacion.ServicioImportacionesRef.DtoSolicitante[] ImportarSolicitantes() {
            return base.Channel.ImportarSolicitantes();
        }
        
        public System.Threading.Tasks.Task<MVC_Presentacion.ServicioImportacionesRef.DtoSolicitante[]> ImportarSolicitantesAsync() {
            return base.Channel.ImportarSolicitantesAsync();
        }
        
        public MVC_Presentacion.ServicioImportacionesRef.DtoProyecto[] ImportarProyectos() {
            return base.Channel.ImportarProyectos();
        }
        
        public System.Threading.Tasks.Task<MVC_Presentacion.ServicioImportacionesRef.DtoProyecto[]> ImportarProyectosAsync() {
            return base.Channel.ImportarProyectosAsync();
        }
    }
}
